import { FaLock, FaPhoneAlt, FaRegHeart, FaShippingFast, FaStar } from "react-icons/fa"
import { FaMoneyCheckDollar } from "react-icons/fa6";

export const NavigationData = [
    {
        text: "Home",
        url: "/"
    },
    {
        text: "About Us",
        url: "/about"
    },
    {
        text: "Products",
        url: "/products"
    },
    {
        text: "Contact Us",
        url: "/contact"
    },
]

export const BannerData = {
    imgUrl: "/assets/images/banner-img.png",
    heading1: "Listen to the",
    spanText: "amazing",
    heading2: "music sound",
    smText: "Experience music like never before",
    btnText: "Shopping Now"
}

export const sliderimg = [
    "/assets/images/img1.png",
    "/assets/images/img2.png",
    "/assets/images/img3.png",
    "/assets/images/img4.png",
    "/assets/images/img5.png",
    "/assets/images/img6.png",
]


export const NewArrivalData = [
    {
        id: 1,
        category: "headbond",
        Feature: "NEW",
        img: "/assets/images/Skullcandy.png",
        title: "Skullcandy - Crusher anc 2 wireless headphones",
        price: 299.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 2,
        category: "headbond",
        Feature: "NEW",
        img: "/assets/images/Beats.png",
        title: "Beats Studio Pro",
        price: 349.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 3,
        category: "headbond",
        Feature: "NEW",
        img: "/assets/images/Sony-WH-CH720N.png",
        title: "Sony - WH-CH720N Wireless Noise Canceling",
        price: 149.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 4,
        category: "earbuds",
        Feature: "NEW",
        img: "/assets/images/Skullcandy-Rail-True-Wireless-Earbuds.png",
        title: "Skullcandy - Rail True Wireless Earbuds",
        price: 79.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 5,
        category: "earbuds",
        Feature: "NEW",
        img: "/assets/images/tws_730_.png",
        title: "Beats Studio Pro",
        price: 224.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 6,
        category: "headbond",
        Feature: "NEW",
        img: "/assets/images/Premium_Noise_Canceling_Headphones.png",
        title: "Premium Noise Canceling Headphones",
        price: 189.99,
        btnText: "Add to cart",
        rating: 5,
    },
];


export const BestSellerData = [
    {
        id: 7,
        category: "headbond",
        Feature: "HOT",
        img: "/assets/images/Sony-WH-CH720N.png",
        title: "Sony - WH-CH720N Wireless Noise Canceling",
        price: 149.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 8,
        category: "earbuds",
        Feature: "HOT",
        img: "/assets/images/tws_730_.png",
        title: "Beats Studio Pro",
        price: 224.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 9,
        category: "earbuds",
        Feature: "HOT",
        img: "/assets/images/Skullcandy-Rail-True-Wireless-Earbuds.png",
        title: "Skullcandy - Rail True Wireless Earbuds",
        price: 79.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 10,
        category: "earbuds",
        Feature: "HOT",
        img: "/assets/images/JBL-Reflect-Flow-Pro-Bluetooth-Truly-Wireless-Sports.png",
        title: "JBL Reflect Flow Pro+ Bluetooth Truly Wireless Sports",
        price: 179.95,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 11,
        category: "headbond",
        Feature: "HOT",
        img: "/assets/images/Bose-QuietComfort-Headphones.png",
        title: "Bose QuietComfort Headphones",
        price: 349.0,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 12,
        category: "headbond",
        Feature: "HOT",
        img: "/assets/images/AKG-Y600NC-Wireless.png",
        title: "AKG Y600NC Wireless",
        price: 349.99,
        btnText: "Add to cart",
        rating: 5,
    },
];


export const advantages = [
    {
        icon: <FaShippingFast className="text-5xl text-black" />,
        text: "Free Shipping",
        subTitle: "Order above $200"
    },
    {
        icon: <FaMoneyCheckDollar className="text-5xl text-black" />,
        text: "Money-back",
        subTitle: "30 days guarantee"
    },
    {
        icon: <FaLock className="text-5xl text-black" />,
        text: "Secure Payments",
        subTitle: "Secured by Stripe"
    },
    {
        icon: <FaPhoneAlt className="text-5xl text-black" />,
        text: "24/7 Support",
        subTitle: "Phone and Email support"
    }
]

export const InstagramData = [
    "/assets/images/instagram1.png",
    "/assets/images/instagram2.png",
    "/assets/images/instagram3.png",
    "/assets/images/instagram4.png",
]

export const HeadphonesData = [
    {
        id: 1,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Skullcandy.png",
        title: "Skullcandy - Crusher anc 2 wireless headphones",
        price: 299.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 2,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Beats.png",
        title: "Beats Studio Pro",
        price: 349.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 3,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Sony-WH-CH720N.png",
        title: "Sony - WH-CH720N Wireless Noise Canceling",
        price: 149.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 4,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Premium_Noise_Canceling_Headphones.png",
        title: "Premium Noise Canceling Headphones",
        price: 189.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 5,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Sennheiser-HD-450BT-Wireless-Headphonesdownload.jpg",
        title: "Sennheiser HD 450BT Wireless Headphones",
        price: 199.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 6,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Bose-QuietComfort-45-Wireless.jpg",
        title: "Bose QuietComfort 45 Wireless",
        price: 329.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 7,
        category: "headphones",
        Feature: "",
        img: "/assets/images/JBL-Quantum-ONE-Gaming-Headset.jpg",
        title: "JBL Quantum ONE Gaming Headset",
        price: 299.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 8,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Audio-Technica-ATH-M50x-Professional.jpg",
        title: "Audio-Technica ATH-M50x Professional",
        price: 149.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 9,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Apple-AirPods-Max-Space-Gray.jpg",
        title: "Apple AirPods Max - Space Gray",
        price: 549.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 10,
        category: "headphones",
        Feature: "",
        img: "/assets/images/Sony-WH-1000XM5-Wireless-Noise-Canceling.jpg",
        title: "Sony WH-1000XM5 Wireless Noise Canceling",
        price: 399.99,
        btnText: "Add to cart",
        rating: 5,
    },
];

export const EarbudsData = [
    {
        id: 1,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Skullcandy-Rail-True-Wireless-Earbuds.png",
        title: "Skullcandy - Rail True Wireless Earbuds",
        price: 79.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 2,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/tws_730_.png",
        title: "Beats Studio Buds",
        price: 224.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 3,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Apple-AirPods-Pro.jpg",
        title: "Apple AirPods Pro (2nd Generation)",
        price: 249.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 4,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Samsung-Galaxy-Buds2-Pro.jpg",
        title: "Samsung Galaxy Buds2 Pro",
        price: 229.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 5,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Jabra-Elite-7-Pro-True-Wireless.jpg",
        title: "Jabra Elite 7 Pro True Wireless",
        price: 199.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 6,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Sony-WF-1000XM4-Wireless-Earbuds.png",
        title: "Sony WF-1000XM4 Wireless Earbuds",
        price: 279.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 7,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Bose-QuietComfort-Earbuds-II.jpg",
        title: "Bose QuietComfort Earbuds II",
        price: 299.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 8,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/OnePlus-Buds-Pro-2.jpg",
        title: "OnePlus Buds Pro 2",
        price: 179.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 9,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Anker-Soundcore-Liberty-4-NC.jpg",
        title: "Anker Soundcore Liberty 4 NC",
        price: 129.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 10,
        category: "earbuds",
        Feature: "",
        img: "/assets/images/Nothing-Ear-Wireless-Earbuds.jpg",
        title: "Nothing Ear (2) Wireless Earbuds",
        price: 149.99,
        btnText: "Add to cart",
        rating: 4,
    },
];

export const AccessoriesData = [
    {
        id: 1,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Premium-Aluminum-Headphone-Stand.jpg",
        title: "Premium Aluminum Headphone Stand",
        price: 49.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 2,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Wireless-Charging-Case-for-Earbuds.jpg",
        title: "Wireless Charging Case for Earbuds",
        price: 39.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 3,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Protective-Carrying-Case-for-Headphones.jpeg",
        title: "Protective Carrying Case for Headphones",
        price: 29.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 4,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Memory-Foam-Earbud-Tips.jpg",
        title: "Memory Foam Earbud Tips (5 Pairs)",
        price: 19.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 5,
        category: "accessories",
        Feature: "",
        img: "/assets/images/3.5mm-Audio-Cable-with-Mic.jpg",
        title: "3.5mm Audio Cable with Mic",
        price: 24.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 6,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Wireless-Bluetooth-Transmitter.jpg",
        title: "Wireless Bluetooth Transmitter",
        price: 34.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 7,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Headphone-Earbud-Cleaning-Kit.jpg",
        title: "Headphone & Earbud Cleaning Kit",
        price: 15.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 8,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Premium-Leather-Replacement-Earpads.jpg",
        title: "Premium Leather Replacement Earpads",
        price: 45.99,
        btnText: "Add to cart",
        rating: 5,
    },
    {
        id: 9,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Braided-USB-C-Charging-Cable.jpg",
        title: "Braided USB-C Charging Cable (2m)",
        price: 18.99,
        btnText: "Add to cart",
        rating: 4,
    },
    {
        id: 10,
        category: "accessories",
        Feature: "",
        img: "/assets/images/Portable-Power-Bank-for-Headphones.jpg",
        title: "Portable Power Bank for Headphones",
        price: 59.99,
        btnText: "Add to cart",
        rating: 5,
    },
];